# Generated by Django 2.2.6 on 2020-04-08 14:54

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=profiles.models.Profile.get_profile_pic_path),
        ),
    ]
